controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_me:
    path: /api/me
    methods: GET
    controller: App\Controller\UserController::me

get_all_users:
    path: /api/users
    methods: GET
    controller: App\Controller\UserController::index

api_register:
    path: /api/register
    methods: POST
    controller: App\Controller\UserController::register

api_login:
    path: /api/login
    methods: POST
    controller: App\Controller\UserController::login

