controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_me:
    path: /api/me
    methods: GET
    controller: App\Controller\UserController::me

get_all_users:
    path: /api/users
    methods: GET
    controller: App\Controller\UserController::index

api_register:
    path: /api/register
    methods: POST
    controller: App\Controller\UserController::register

api_login:
    path: /api/login
    methods: POST
    controller: App\Controller\UserController::login

create_project:
    path: /api/project/create
    methods: POST
    controller: App\Controller\ProjectController::create

update_project:
    path: /api/project/update/{id}
    methods: PUT
    controller: App\Controller\ProjectController::update

find_project:
    path: /api/project/find/{id}
    methods: GET
    controller: App\Controller\ProjectController::find

app_project:
    path: /api/project
    methods: GET
    controller: App\Controller\ProjectController::index

delete_project:
    path: /api/project/delete/{id}
    methods: DELETE
    controller: App\Controller\ProjectController::delete



create_task:
    path: /api/tasks/create
    methods: POST
    controller: App\Controller\TaskController::create


app_task:
    path: /api/tasks
    methods: GET
    controller: App\Controller\TaskController::index

